### ISSUE TITLE
analogSetWidth() not supported for ESP32-S3

### ISSUE THREAD

**Issue by jetpax** [marlinarnz/eVCU#3]
eVCU fails to compile for ESP32-S3 with 
```
src/Pedal.cpp:26:3: error: 'analogSetWidth' was not declared in this scope
```

I found that 

```C++
 analogReadResolution(ADC_WIDTH);
```
seems to work fine as a replacement

**Comment by marlinarnz** [comment]
Thanks, that's good to know. I replaced it accordingly: f2229a63e9676eaebe475443f6f68b134e300d1a

However, the ESP32 ADC is buggy in general. I opened another issue on it: #4
